aws-acceptance-test:
  variables:
    CUCUMBER_OPTIONS: "@default or @health or @SpatialLongitudeExtendedRange"
    GROUP_ID: $DOMAIN
  script:
    - >
      set -euxo pipefail &&
      cd $ACCEPTANCE_TEST_DIR &&
      $MAVEN 
      verify 
      -Dallure.results.directory=aws/allure-results
      -DdisableXmlReport=true
      --quiet
      --update-snapshots
      -Dcucumber.filter.tags="${CUCUMBER_OPTIONS}" | tee test-results.log
  artifacts:
    when: always
    paths:
      - test-results.log
      - $ACCEPTANCE_TEST_DIR/aws/allure-results/
