#####################
# README: Defines a template to be used as a starting point for defining a service pipeline
#####################

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - /**/*.md
      - .gitignore
      - images/

pr:
  autoCancel: false
  branches:
    include:
      - "*"
    exclude:
      - master
  paths:
    exclude:
      - /**/*.md
      - .gitignore
      - images/

resources:
  repositories:
    - repository: infrastructure-templates
      type: git
      name: open-data-ecosystem/infrastructure-templates

variables:
  - group: "Azure Common Secrets"
  - group: "Azure - Common"

  - name: serviceName
    value: "search"

stages:
  - template: devops/service-pipelines/build-stage.yml@infrastructure-templates
    parameters:
      mavenPublishJUnitResults: true
      mavenOptions: "--settings ./search-core/maven/settings.xml -DVSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN) -U"
      copyFileContents: |
        pom.xml
        provider/search-azure/maven/settings.xml
        provider/search-azure/pom.xml
        provider/search-azure/target/*-spring-boot.jar
      copyFileContentsToFlatten: |
        provider/search-gc/target/*-spring-boot.jar
        provider/search-gc/src/main/appengine/app.yaml
        provider/search-gc/src/main/resources/application.properties
        provider/search-gc/scripts/deploy.sh
        provider/search-integration-tests.zip
      serviceBase: ${{ variables.serviceName }}
      testingRootFolder: "testing"
  - template: devops/service-pipelines/deploy-stages.yml@infrastructure-templates
    parameters:
      serviceName: ${{ variables.serviceName }}
      testCoreMavenPomFile: "search-test-core/pom.xml"
      testCoreMavenOptions: "--settings $(System.DefaultWorkingDirectory)/drop/deploy/maven/settings.xml -DVSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN)"
      providers:
        - name: Azure
          # Merges into Master
          ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
            environments: ["devint", "qa", "prod"]
          # PR updates / creations
          ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
            environments: ["devint"]
