variables:
  CIMPL_SERVICE: "search"
  CIMPL_TESTING_DIR: "testing"
  CIMPL_BUILD_PATH: "search-core-plus/cloudbuild/Dockerfile"
  DISABLE_INTEGRATION_TEST: true

# osdu-main jobs
cimpl-dev-acceptance-test:
  variables:
    DEFAULT_DATA_PARTITION_ID_TENANT2: non-exist
    CUCUMBER_OPTIONS: "@default or @health or @SpatialLongitudeStandardRange"

cimpl-dev-backup-acceptance-test:
  variables:
    DEFAULT_DATA_PARTITION_ID_TENANT2: non-exist
    CUCUMBER_OPTIONS: "@default or @health or @SpatialLongitudeStandardRange"

cimpl-prod-acceptance-test:
  variables:
    DEFAULT_DATA_PARTITION_ID_TENANT2: non-exist
    CUCUMBER_OPTIONS: "@default or @health or @SpatialLongitudeStandardRange"