seed = 42424242424424242
workers = 1
continue-on-failure = true
request-timeout = 30.0
hooks="./hooks/hooks.py"

[generation]
mode = "all"
max-examples = 500

[phases.stateful]
enabled = false

[phases.examples]
enabled = true

[phases.coverage]
enabled = true

[phases.fuzzing]
enabled = true

[reports.junit]
path = "./output/junit/junit.xml"

[reports.allure]
path = "./output/allure/results"
